FROM php:8.4-cli-trixie

COPY --from=ghcr.io/bsn4/grpc-php-rs:latest-php8.4 /usr/local/ /usr/local/

RUN apt-get update && apt-get install -y --no-install-recommends \
        git \
        unzip \
        protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

RUN pecl install protobuf \
    && docker-php-ext-enable protobuf

WORKDIR /workspace

CMD ["bash"]
