FROM php-grpc-lite-fpm-lifecycle-16

RUN apt-get update && apt-get install -y --no-install-recommends \
        linux-perf \
        procps \
        strace \
        valgrind \
    && rm -rf /var/lib/apt/lists/*
