#ifndef PHP_GRPC_LITE_GRPC_CONSTANTS_H
#define PHP_GRPC_LITE_GRPC_CONSTANTS_H

/*
 * Shared gRPC wire/API constants.
 *
 * This header intentionally has no PHP/Zend dependency so protocol helpers,
 * C unit tests, and PHP boundary code can use the same values without reading
 * common.h.
 */

#define GRPC_STATUS_OK 0
#define GRPC_STATUS_CANCELLED 1
#define GRPC_STATUS_UNKNOWN 2
#define GRPC_STATUS_INVALID_ARGUMENT 3
#define GRPC_STATUS_DEADLINE_EXCEEDED 4
#define GRPC_STATUS_NOT_FOUND 5
#define GRPC_STATUS_ALREADY_EXISTS 6
#define GRPC_STATUS_PERMISSION_DENIED 7
#define GRPC_STATUS_RESOURCE_EXHAUSTED 8
#define GRPC_STATUS_FAILED_PRECONDITION 9
#define GRPC_STATUS_ABORTED 10
#define GRPC_STATUS_OUT_OF_RANGE 11
#define GRPC_STATUS_UNIMPLEMENTED 12
#define GRPC_STATUS_INTERNAL 13
#define GRPC_STATUS_UNAVAILABLE 14
#define GRPC_STATUS_DATA_LOSS 15
#define GRPC_STATUS_UNAUTHENTICATED 16

#define GRPC_OP_SEND_INITIAL_METADATA 0
#define GRPC_OP_SEND_MESSAGE 1
#define GRPC_OP_SEND_CLOSE_FROM_CLIENT 2
#define GRPC_OP_RECV_INITIAL_METADATA 4
#define GRPC_OP_RECV_MESSAGE 5
#define GRPC_OP_RECV_STATUS_ON_CLIENT 6

#endif /* PHP_GRPC_LITE_GRPC_CONSTANTS_H */
